from __future__ import annotations


class CoreException(Exception):
    pass
